export const REDUX_ACTIONS = {
    COUNTER: {

    },
    PRODUCTS: {
        FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
        FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
        FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
    }
}